"""Export an IO-VNBD smartphone CSV into browser replay data.

Usage:
    python tools/export_iovnbd_replay.py \
        --smartphone S-S2.csv \
        --output mobile/demo_data.js

This keeps the raw IO-VNBD files out of the repository. The generated JS is
small enough for the mobile MVP and contains only timestamp, GNSS position,
speed and course. During an outage the browser uses speed + heading as a
replay dead-reckoning proxy; it is intentionally NOT presented as the final
IMU DR engine.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd


def clean(name: str) -> str:
    name = name.strip()
    name = re.sub(r"[\\r\\n\\t]", "", name)
    return re.sub(r"\\s+", " ", name)


def find_col(columns, pattern: str) -> str:
    rx = re.compile(pattern, re.IGNORECASE)
    for col in columns:
        if rx.search(col):
            return col
    raise KeyError(f"Could not find column matching {pattern!r}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--smartphone", required=True, help="IO-VNBD smartphone CSV")
    parser.add_argument("--output", default="mobile/demo_data.js")
    parser.add_argument(
        "--speed-scale",
        type=float,
        default=3.6,
        help="Multiply CSV GPS SPEED by this factor before converting km/h to m/s; 3.6 matches the observed IO-VNBD Android speed encoding.",
    )
    parser.add_argument("--max-points", type=int, default=2500)
    args = parser.parse_args()

    df = pd.read_csv(args.smartphone, skipinitialspace=True, encoding="latin1")
    df.columns = [clean(c) for c in df.columns]

    lat = find_col(df.columns, r"gps latitude")
    lon = find_col(df.columns, r"gps longitude")
    speed = find_col(df.columns, r"gps speed")
    heading = find_col(df.columns, r"gps orientation|gps heading")

    # DATE is preferred because some IO-VNBD recordings reset TIME SINCE START.
    date_col = next((c for c in df.columns if c.upper() == "DATE"), None)
    time_col = next((c for c in df.columns if re.search(r"time since start", c, re.I)), None)

    if date_col:
        timestamps = pd.to_datetime(df[date_col], errors="coerce")
        elapsed = (timestamps - timestamps.iloc[0]).dt.total_seconds()
    elif time_col:
        raw = pd.to_numeric(df[time_col], errors="coerce")
        elapsed = (raw - raw.iloc[0]) / 1000.0
    else:
        raise KeyError("IO-VNBD file has neither DATE nor TIME SINCE START")

    out = pd.DataFrame(
        {
            "t": elapsed,
            "lat": pd.to_numeric(df[lat], errors="coerce"),
            "lon": pd.to_numeric(df[lon], errors="coerce"),
            "speed": pd.to_numeric(df[speed], errors="coerce") * args.speed_scale / 3.6,
            "heading": pd.to_numeric(df[heading], errors="coerce"),
        }
    ).dropna()

    # Remove duplicate/non-monotonic timestamps and impossible GPS fixes.
    out = out[(out["lat"].between(-90, 90)) & (out["lon"].between(-180, 180))]
    out = out.sort_values("t").drop_duplicates("t")

    if len(out) > args.max_points:
        idx = np.linspace(0, len(out) - 1, args.max_points).round().astype(int)
        out = out.iloc[np.unique(idx)]

    records = []
    for row in out.itertuples(index=False):
        records.append(
            {
                "t": round(float(row.t), 3),
                "lat": round(float(row.lat), 8),
                "lon": round(float(row.lon), 8),
                "speed": round(max(0.0, float(row.speed)), 3),
                "heading": round(float(row.heading) % 360.0, 2),
            }
        )

    payload = {
        "source": "IO-VNBD smartphone replay",
        "speed_unit": "m/s",
        "heading_unit": "deg, clockwise from north",
        "note": "Replay proxy: GNSS speed/course are propagated during simulated outage. Final app must replace this with the IMU DR engine.",
        "points": records,
    }

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by tools/export_iovnbd_replay.py; do not edit manually.\n"
        "window.DEMO_TRAJECTORY = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(records)} replay points to {output}")


if __name__ == "__main__":
    main()
